baseURL = "https://roquen4145.github.io/"
languageCode = "ko-kr"
title = "Quiet Systems"
defaultContentLanguage = "ko"
enableRobotsTXT = true
enableGitInfo = true
paginate = 10
summaryLength = 40
assetDir = "assets"
disableKinds = ["taxonomy", "term", "RSS"]

[permalinks]
  "/" = "/:sections/:slug/"

[params]
  description = "Second Order Thinking"
  searchIndex = "index.json"
  [params.analytics]
    provider = "plausible"
    domain = "roquen4145.github.io"
    script = "https://plausible.io/js/script.js"
    enabled = false

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML"]
  page = ["HTML"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[privacy]
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
